# Generated by Django 3.1.3 on 2020-11-12 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('pub_date', models.DateField(default=datetime.datetime(2020, 11, 12, 9, 39, 12, 627998))),
            ],
        ),
    ]
