# Generated by Django 3.1.3 on 2020-11-16 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_auto_20201115_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 12, 22, 28, 877048)),
        ),
    ]
