# Generated by Django 3.1.3 on 2020-11-17 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_auto_20201116_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 12, 32, 13, 336241)),
        ),
    ]
